### ISSUE TITLE
No module found with name [nimble-login]

### ISSUE THREAD

**Issue by jedi-jiang** [snimavat/nimble#57]
I use the plugin version 0.7 in Grails 2.4.4 and run the web-app successfully after resolved some dependency problems. When i navigate to "http://localhost:8080/dhydb/main" the following exception occurred:

URI
    /dhydb/login
Class
    java.lang.IllegalArgumentException
Message
    No module found with name [nimble-login]
![grails runtime exception](https://cloud.githubusercontent.com/assets/2793708/4956833/3f980a64-669f-11e4-9f72-8176b877b1e5.png)

**Comment by snimavat** [comment]
No longer an issue with asset pipeline
